#!/bin/sh

source_language='en'

project_root="$(dirname "$(realpath "$0")")"

if [ $# -lt 1 ]; then
    # set foreground color to red
    tput setaf 1 2>/dev/null

    printf '%s\n' "Usage: LANGUAGE [MAKE OPTIONS]..."
    printf '%s\n' "Runs the project makefile with LANGUAGE configured."
    printf '%s\n' "LANGUAGE must be a language code such as fr, ko, it, ..."

    # reset foreground color
    tput sgr0 2>/dev/null
    exit 1
fi >&2

run_make() {
    exec make -C "${project_root}" "$@"
}

language="$1"
shift

export BUILDDIR="_build_${language}"
if [ "${language}" = "${source_language}" ]; then
    run_make "$@"
else
    run_make -e SPHINXOPTS="-D language='${language}'" "$@"
fi
