#!/usr/bin/env bash
if [ -z $ORG_DIR ]
then
ORG_DIR=`find $HOME/.emacs.d/elpa -type d -depth 1 -regex ".*org-[0-9]*"`

set -e
fi

emacs -Q --batch \
      --eval "(add-to-list 'load-path \"$ORG_DIR\")" \
      --eval "(require 'org)" \
      --eval "(setq org-latex-listings 'minted)" \
      --eval "(setq org-confirm-babel-evaluate nil)" \
      --visit=$1 --funcall org-latex-export-to-latex
