#!/usr/bin/env bash

set -e

if [[ -z "${ORG_DIR}" ]]; then
    ORG_DIR="$(find $HOME/.emacs.d/elpa -maxdepth 1 -type d -regex '.*org\(-plus-contrib\)*-[0-9]*')"
    # -maxdepth *is* a GNUism, but it's been ported everywhere by now.
fi

if [[ -d "$ORG_DIR" ]]; then
    emacs -Q --batch \
        --eval "(add-to-list 'load-path \"$ORG_DIR\")" \
        --eval "(require 'org)" \
        --eval "(setq org-confirm-babel-evaluate nil)" \
        --visit="$1" --funcall org-latex-export-to-latex
else
    echo "No org-mode directory found."
fi
